---
title: "Historial de cambios a las rutinas nimble"
output: pdf_document
date: "2025-02-24"
---

# RutinasNimble.0.1

* Rutinas originales. Contiene la función pnimble y load_leroux.

# RutinasNimble.0.2

* Incorpora HMC.
* Adaptación de la distribución de Leroux para que soporte métodos hamiltonianos.
* Mejora avisos por ntfy mediante una función específica más elaborada.
* Posibilidad de elección de métodos concretos de simulación de variables más allá de los métodos default.
* Incorporación de opción parallel.
* Incorporación de restricción de suma cero a leroux.
* Poner como muestreador por default para leroux RW univariante.
* Cambiar argumento sd.theta a sd.
* Chequear ordenación en from.to.
* Fixed en argumento monitor (no funcionaba)

# RutinasNimble.0.3

* Incorporación de distribución SPDE.
* Mejora de distribución de Leroux evitando un buen número de derivadas tal y como se hace en dSPDE.
* Para WAIC=TRUE quito una de las compilaciones en la compilación final del modelo ya que parece no hacer falta. También quito el buildDerivs=TRUE porque también entiendo que no es necesario, todo esto aligera la ejecución del modelo.
* La función de carga load.leroux empieza deregistrando esa distribución por si estuviera previamente cargada y ha sufrido alguna modificación.
* Summaries no se calculan si una variable no tiene variabilidad o tiene NAs (antes daba un error).

TODO:
* Con on.exit ejecutar siempre notify y devolver objeto aunque fallen partes posteriores de la función.